### ISSUE TITLE
Cannot build on Ubuntu 20.10

### ISSUE THREAD

**Issue by dzfranklin** [endoli/lldb-sys.rs#8]
# System info

```
> lsb_release -a
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
```

```
> uname -a
Linux daniel-darter 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

```
> llvm-config --version
11.0.0
```

Reproduced on lldb-sys.rs HEAD, v0.0.21, and v0.0.20. Didn't check older.

# To reproduce

```bash
> gh repo clone endoli/lldb-sys.rs
> cd lldb-sys.rs
> cargo build
```

# The error

```
src/lldb/Bindings/SBCommandInterpreterBinding.cpp: In function ‘SBCommandInterpreterRunOptionsOpaque* CreateSBCommandInterpreterRunOptions()’:
  src/lldb/Bindings/SBCommandInterpreterBinding.cpp:22:99: error: invalid use of incomplete type ‘class lldb::SBCommandInterpreterRunOptions’
     22 |     return reinterpret_cast<SBCommandInterpreterRunOptionsRef>(new SBCommandInterpreterRunOptions());
        |                                                                                                   ^
  In file included from /usr/lib/llvm-11/include/lldb/API/SBBreakpoint.h:12,
                   from src/lldb/Bindings/SBBreakpointBinding.h:15,
                   from src/lldb/Bindings/LLDBBinding.h:21,
                   from src/lldb/Bindings/SBCommandInterpreterBinding.cpp:10:
```
([full stderr](https://gist.github.com/danielzfranklin/d9c3bd31e46961f730215ed82a360fee))

**Comment by dzfranklin** [comment]
This seems to be caused by an update to llvm that needed a new header include. PR #9  adds it.
